trigger:
  branches:
    include:
    - main
  paths:
    include:
    - modules/azuresecrets/*

pool:
  vmImage: 'windows-2019'  # Change this to 'windows-2022' or your custom agent if necessary

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
      Install-Module -Name Az.Accounts -Force -AllowClobber -Scope CurrentUser
      Install-Module -Name Az.KeyVault -Force -AllowClobber -Scope CurrentUser
      $Module = Get-Module -Name Az.Accounts, Az.KeyVault -ListAvailable
      if (-not $Module) {
        Write-Error "Failed to install Az modules"
        Exit 1
      }

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
      #Import the PowerShellGet module
      Import-Module PowerShellGet -Force
      
      $modulePath = "modules/azuresecrets"
      
      #Publish the module to the PowerShell Gallery
      Publish-Module -Path $modulePath -NuGetApiKey "$(PowerShellGalleryApiKey)" -Force
  displayName: 'Publish Module to PowerShell Gallery'
